GET http://localhost:8080/monster/list HTTP/1.1

###
GET http://localhost:8080/monster/19/show HTTP/1.1

###
GET http://localhost:8080/monster/22/delete HTTP/1.1

###
GET http://localhost:8080/monster/22/edit HTTP/1.1

###
POST http://localhost:8080/monster/create HTTP/1.1
Content-Type: application/json

{
  "id": 101,
  "name": "Felpa",
  "last_updated": "2021-09-02",
  "attack_level": 1,
  "defence_slash": 20,
  "size": 2,
  "hitpoints": 90,
  "category": [
    "Cat A",
    "Cat B",
    "Cat C"
  ],
  "examine": "A very smelly ghost.",
  "wiki_url": "https://oldschool.runescape.wiki/w/Aberrant_spectre"
}